final availableSports = [
 "Fútbol 11",
    "Fútbol sala",
    "Fútbol playa",
    "Baloncesto",
    "Baloncesto 3x3",
    "Vóley",
    "Vóley playa",
    "Béisbol",
    "Sóftbol",
    "Rugby 15",
    "Rugby 7",
    "Fútbol americano",
    "Flag football",
    "Balonmano",
    "Polo",
    "Cricket",
    "Hockey sobre césped",
    "Hockey sobre hielo",
    "Hockey en línea",
    "Waterpolo",
    "Ultimate Frisbee",
    "Quidditch",
    "Curling",
    "Dodgeball (quemados)",
    "Remo en equipo",
    "Dragon boat",
    "Bobsleigh",
    "Powerlifting",
    "Halterofilia",
    "CrossFit",
    "Calistenia",
    "Street workout",
    "Entrenamiento con mancuernas (dumbbells)",
    "Entrenamiento con barra (barbell)",
    "TRX",
    "Kettlebells",
    "Running",
    "Trail running",
    "Ultramaratón",
    "Ciclismo de ruta",
    "Ciclismo de pista",
    "Ciclismo de montaña",
    "Spinning",
    "Natación",
    "Indoor rowing",
    "Marcha atlética",
    "Escalada deportiva",
    "Escalada boulder",
    "Escalada tradicional",
    "Patinaje sobre hielo",
    "Patinaje en línea",
    "Senderismo",
    "Esquí alpino",
    "Esquí de fondo",
    "Esquí de travesía",
    "Snowboard",
    "Surf",
    "Paddle surf",
    "Windsurf",
    "Kitesurf",
    "Boxeo",
    "Kickboxing",
    "Muay Thai",
    "Jiu-Jitsu brasileño (BJJ)",
    "Judo",
    "Taekwondo",
    "Karate",
    "Lucha grecorromana",
    "Lucha libre",
    "MMA",
    "Esgrima",
    "Kendo",
    "Yoga",
    "Pilates",
    "Tai Chi",
    "Qi Gong",
    "Meditación en movimiento",
    "Flow arts",
    "Equitación",
    "Motociclismo",
    "Motocross",
    "Karting",
    "Automovilismo",
    "Pesca deportiva",
    "Caza deportiva",
    "Tiro con arco",
    "Tiro deportivo",
    "Golf",
    "Bolos",
    "Billar",
    "Pool",
    "Snooker",
    "Dardos",
    "Ajedrez",
    "Esports",
    "Paracaidismo",
    "Parapente",
    "Escalada libre",
    "Slackline",
    "BMX",
    "Skate",
    "Longboard",
    "Parkour",
    "Base Jump",
    "Wakeboard",
    "Cross Training",
    "HIIT",
    "Bootcamp",
    "Zumba",
    "Baile fitness",
    "Aeróbic",
    "Circuit Training",
    "Entrenamiento militar",
    "Spartan Race",
];